kind: Service
apiVersion: v1
metadata:
  name: mypivot4-backend-service
spec:
  type: ClusterIP
  selector:
    run: mypivot4-backend
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  - name: https
    port: 8443
    targetPort: 8443

