apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8tz.io/injected: "true"
    k8tz.io/timezone: Europe/Rome
  name: mypivot4-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mypivot4-backend
  template:
    metadata:
      annotations:
        k8tz.io/injected: "true"
        k8tz.io/timezone: Europe/Rome
      labels:
        run: mypivot4-backend
    spec:
      containers:
      - env:
        - name: FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX
          value: mypivot4_backend.access
        - name: TZ
          value: Europe/Rome
        envFrom:
        - secretRef:
            name: mypivot4-fluent-config-secret
        image: _REGISTRY_ENTE_/common/mypay4-fluentd:latest
        imagePullPolicy: Always
        name: fluentd-agent
        resources:
          limits:
            cpu: "0.5"
            memory: 1Gi
          requests:
            cpu: "0.1"
            memory: 100Mi
        volumeMounts:
        - mountPath: /mypivot4/logs
          name: access-logs
        - mountPath: /fluentd/etc
          name: mypivot4-be-fluent-config
        - mountPath: /etc/localtime
          name: k8tz
          readOnly: true
          subPath: Europe/Rome
        - mountPath: /usr/share/zoneinfo
          name: k8tz
          readOnly: true
      - env:
        - name: TZ
          value: Europe/Rome
        envFrom:
        - secretRef:
            name: mypivot4-artemis-user-creds-secret
        - secretRef:
            name: mypivot4-mypay4-user-creds-secret
        - secretRef:
            name: mypivot4-user-creds-secret
        - configMapRef:
            name: mypivot4-javaopts-config
        - configMapRef:
            name: mypivot4-be-config
        image: _REGISTRY_ENTE_/mypivot4/mypivot4-be:latest
        imagePullPolicy: Always
        name: mypivot4-backend
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8081
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 2Gi
        volumeMounts:
        - mountPath: /mypivot4/logs
          name: access-logs
        - mountPath: /E45
          name: conf
        - mountPath: /etc/localtime
          name: k8tz
          readOnly: true
          subPath: Europe/Rome
        - mountPath: /usr/share/zoneinfo
          name: k8tz
          readOnly: true
      imagePullSecrets:
      - name: registry-_ENTE_-secret
      securityContext:
        fsGroup: 9001
        runAsGroup: 9001
        runAsUser: 9002
      terminationGracePeriodSeconds: 60
      volumes:
      - name: conf
        persistentVolumeClaim:
          claimName: mypay4-claim
      - emptyDir: {}
        name: access-logs
      - configMap:
          name: mypivot4-be-fluent-config
        name: mypivot4-be-fluent-config
      - hostPath:
          path: /usr/share/zoneinfo
        name: k8tz
