apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypivot4-batch-load-flussi-rendicontazione
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypivot4-batch-load-flussi-rendicontazione
      job: batch
      queue-name: "RENDICONTAZIONE_STANDARD"
  template:
    metadata:
      labels:
        app: mypivot4-batch-load-flussi-rendicontazione
        job: batch
        queue-name: "RENDICONTAZIONE_STANDARD"
    spec:
      containers:
        - name: fluentd-agent
          image: _REGISTRY_ENTE_/common/mypay4-fluentd:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.1"
            limits:
              memory: "1Gi"
              cpu: "0.5"
          env:
            - name: FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX
              value: "mypivot4_batch_import_rendicontazione.access"
          envFrom:
            - secretRef:
                name: mypivot4-fluent-config-secret
          volumeMounts:
          - name: access-logs
            mountPath: /var/log/batch		  
        - name: mypivot4-batch-load-flussi-rendicontazione
          image: _REGISTRY_ENTE_/mypivot4/mypivot4-batch-load-flussi-rendicontazione:latest
          command: ["/batch/bin/BatchLoadFlussiRendicontazione_run.sh"]
          volumeMounts:
          - name: conf
            mountPath: /E45
          - name: access-logs
            mountPath: /var/log/batch	
          - name:  mypivot4-batch-load-flussi-rendicontazione-configs
            mountPath: /conf/loadflussirendicontazione-properties_1.0.properties
            subPath: loadflussirendicontazione-properties_1.0.properties
          - name: mypivot4-batch-load-flussi-rendicontazione-configs
            mountPath: /conf/log4j.xml
            subPath: log4j.xml
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: "mypivot4-user-creds-secret"
          - secretRef:
              name: "mypivot4-artemis-user-creds-secret"
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.1"
            limits:
              memory: "512Mi"
              cpu: "100m"
      volumes:
      - name: conf
        persistentVolumeClaim:
          claimName: mypay4-claim
      - name: mypivot4-batch-load-flussi-rendicontazione-configs
        configMap:
          name: mypivot4-batch-load-flussi-rendicontazione-configs
      - name: access-logs
        emptyDir: {}
      imagePullSecrets:
      - name: registry-_ENTE_-secret

